### ISSUE TITLE
Scale seems to not be working

### ISSUE THREAD

**Issue by Bowarc** [NemuiSen/ggegui#18]
Hey, it's me again ! 
I think i found another bug (or i didn't understood something)

Settings the scale with `gui.input.set_scale_factor(5.5, ctx.gfx.size());` 
(I used the `example/basic_template.rs` and modified only the following: )
```rust
struct State {
	gui: Gui,
}

impl State {
	pub fn new(ctx: &mut Context) -> Self {
		let mut gui = Gui::new(ctx);
		gui.input.set_scale_factor(5.5, ctx.gfx.size());
		Self { gui }
	}
}
```
seems to have no effect on the size of the egui window

Am i missunderstanding something ?

**Comment by Bowarc** [comment]
Fixed with pull [request 19](https://github.com/NemuiSen/ggegui/pull/19)

**Comment by NemuiSen** [comment]
Thanks for the help
