### ISSUE TITLE
Focus/Cursor position is changing too fast

### ISSUE THREAD

**Issue by martinstarman** [NemuiSen/ggegui#24]
Steps to reproduce:
- copy the minimal example from readme
- add multiple buttons
- run project
- by pressing Tab key, change focus between buttons

or

- copy the minimal example from readme
- add singleline edit
- run project
- type some text into edit
- press left or right arrow key

Is almost imposible to move focus to first button or move cursor one position to the left or right.

**Comment by m-r-hunt** [comment]
I've opened a pull request that addresses this issue: https://github.com/NemuiSen/ggegui/pull/27
