### ISSUE TITLE
Semi-automatic dependency update with dependabot

### ISSUE THREAD

**Issue by dallenng** [NemuiSen/ggegui#26]
Hello, would you like a PR that setup dependabot for your repo ?
I also notice that you don't build the code in CI, I could add that as well if you want ?

# Context

[Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates) is a tool provided by Github to automatically create PR with dependency update. It can update Rust and Github Actions dependencies. That way you will be notified when an update is available.

Dependabot can run daily, weekly or monthly. I think weekly is great for this project to keep up with `ggez` and `egui` without running it too frequently.

What do you think ?

**Comment by NemuiSen** [comment]
I think it's a good idea, especially because I don't know how to use those github features (actually I don't even know how did i made when someone do a "push" automatically apply an identation style correction).
So feel free to add whatever you think is most appropriate for this repo (and btw explain me a little bit about it).

**Comment by dallenng** [comment]
For the dependabot part, it's a configuration file to tell the bot what package manager the repo uses and how frequently the bot should scan the repo. If it's set to weekly, the bot will scan every monday if dependencies can be updated. If a dependency can be updated, the bot will create a PR that update the dependency, if you want the update, you merge the PR.

For the CI part, it is more common to check code format and fail if the code is not formatted instead of automatically push format commit, because it can be confusing for people making a PR. I can leave it as is, or change it if you want.
I can add a job that run `cargo clippy` on linux, windows and macos, that way, when someone or the bot make a PR, you know if it compiles on the three platforms and catch common mistakes.
